name: Deploy lab3 Javadoc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Javadoc
        run: |
          rm -rf tmp/site
          mkdir -p tmp/site
          javadoc -d tmp/site src/lab3/*.java

      - name: Deploy Javadoc to gh-pages
        env:
          REPO: ${{ github.repository }}
        run: |
          git clone --branch gh-pages https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ env.REPO }} gh-pages
          cd gh-pages

          git rm -r --ignore-unmatch lab3 || true
          git rm -r --ignore-unmatch src || true

          rm -rf lab3
          mkdir -p lab3
          cp -r ../tmp/site/* ./lab3/

          touch lab3/.nojekyll

          echo "=== gh-pages root ==="
          ls -la
          echo "=== lab3 content ==="
          ls -la lab3 || true
          echo "=== tmp/site content (should contain index.html) ==="
          ls -la ../tmp/site || true

          git add -A
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "docs: update lab3 Javadoc" || echo "no changes to commit"
          git push origin gh-pages --force
